---
- name: Download WordPress  
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: copy current archive for gitlab
  ansible.builtin.fetch:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    flat: yes
    
    
- name: Extract WordPress  
  unarchive: 
    src=/tmp/wordpress.tar.gz 
    dest=/var/www/ 
    copy=no
- name: update ports.conf for apache
  template:
    src=templates/ports.conf
    dest=/etc/apache2/ports.conf

- name: Update default Apache site
  lineinfile: 
    dest=/etc/apache2/sites-enabled/000-default.conf 
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: place wp config file
  template:
    src=templates/wp-config.php
    dest=/var/www/wordpress/wp-config.php

- name: Recursively change ownership of a wordpress directory
  ansible.builtin.file:
    path: /var/www/wordpress
    state: directory
    recurse: yes
    owner: vagrant
    group: vagrant


- name: copy current wp-config for gitlab
  ansible.builtin.fetch:
    src: /var/www/wordpress/wp-config.php
    dest: /tmp/
    flat: yes



#- name: Copy sample config file
#  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

#- name: Update WordPress config file
#  ansible.builtin.replace:
#    path: /var/www/wordpress/wp-config.php
#    regexp: 'localhost'
#    replace: "{{ mysql_master_ip }}" 

#- name: Update WordPress config file
#  ansible.builtin.replace:
#    path: /var/www/wordpress/wp-config.php
#    regexp: 'username_here'
#    replace: "{{ wordpress_login }}"
#- name: Update WordPress config file
#  ansible.builtin.replace:
#    path: /var/www/wordpress/wp-config.php
#    regexp: 'password_here'
#    replace: "{{ wordpress_password }}"
#- name: Update WordPress config file
#  ansible.builtin.replace:
#    path: /var/www/wordpress/wp-config.php
#    regexp: 'database_name_here'
#    replace: "{{ wordpress_login }}"

