#- name: Set hostname
#  hostname:
#    name: "{{ inventory_hostname }}"

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600


- name: Install Nginx Web Server on Debian Family
  apt:
    name=nginx
    state=latest
  when:
    ansible_os_family == "Debian"
  notify:
    - nginx systemd

- name: install certbot for letsencrypt
  apt:
    name=certbot
    state=latest

- name: Replace nginx.conf
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf

- name: copy .htpasswd
  copy:
    src: templates/.htpasswd
    dest: /etc/nginx/.htpasswd
    owner: root
    group: root
    mode: 0444



- name: place vhost
  template:
    #src=templates/www.netology.tech.conf
    src=templates/template.conf
    dest=/etc/nginx/sites-enabled/{{ item.fqdn }}.conf
  with_items: "{{ sites }}"


- name: Remove default host
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent


- name: Check that the somefile.conf exists
  stat:
    path: /etc/letsencrypt/live/www.netology.tech/fullchain.pem
  register: stat_result

- name: stop nginx for create certs
  systemd:
    name: nginx
    enabled: yes
    state: stopped
  when: not stat_result.stat.exists
  

- name: Create certificates, if not exist
  command: "certbot --test-cert --no-eff-email --standalone certonly -m ivanov@unix-server.su --agree-tos -d www.netology.tech,alertmanager.netology.tech,grafana.netology.tech,gitlab.netology.tech,prometheus.netology.tech,app.netology.tech"
  when: not stat_result.stat.exists

- name: copy ssh key
  copy:
    src: /home/vagrant/.ssh/id_rsa
    dest: /home/vagrant/.ssh/id_rsa
    owner: vagrant
    group: vagrant 
    mode: 0600








