---
  - name: setup cicd 
    hosts: gitlab.netology.tech
    become: true
    gather_facts: no
    remote_user: vagrant
    tasks:
    - name: check root password for gitlab
      ansible.builtin.raw: "cat  /etc/gitlab/initial_root_password| grep 'Password:' | awk '{print $2}'|tr -d '\r\n'"
      register: gitlab_password
    - name: print password
      debug:
        msg: "{{  gitlab_password['stdout']  }}"
  
#    - name: find runner registration token
#      ansible.builtin.command: gitlab-rails runner -e production "puts Gitlab::CurrentSettings.current_application_settings.runners_registration_token"
      register: gitlab_token
#    - name: print token for runner
#      debug:
#        msg: "{{ gitlab_token['stdout'] }}"
#    - name: save token to tmp file
#      local_action: copy content={{ gitlab_token.stdout }} dest=/tmp/token.txt

    - name: Create GitLab Project
      community.general.gitlab_project:
        api_url: http://127.0.0.1/
        api_token: "FL2sBqCrSQDzp5S4xFu7" 
        name: my_first_project
