---
  - name: prepare gitlab
    hosts: gitlab.netology.tech
    become: true
    gather_facts: no
    remote_user: vagrant
    tasks:
    - name: check root password for gitlab
      ansible.builtin.raw: "cat  /etc/gitlab/initial_root_password| grep 'Password:' | awk '{print $2}'|tr -d '\r\n'"
      register: gitlab_password
    - name: print password
      debug:
        msg: "{{  gitlab_password['stdout']  }}"

    - name: save password to tmp file
      local_action: copy content={{ gitlab_password.stdout }} dest=/tmp/password.txt
  
    - name: find runner registration token
      ansible.builtin.command: gitlab-rails runner -e production "puts Gitlab::CurrentSettings.current_application_settings.runners_registration_token"
      register: gitlab_token
    - name: print token for runner
      debug:
        msg: "{{ gitlab_token['stdout'] }}"
    - name: save token to tmp file
      local_action: copy content={{ gitlab_token.stdout }} dest=/tmp/token.txt


    - name: add iptables rule for node_exporter
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 19100
        jump: ACCEPT
      
    - name: copy ssh key
      copy:
        src: /home/vagrant/.ssh/id_rsa
        dest: /home/vagrant/.ssh/id_rsa
        owner: vagrant
        group: vagrant
        mode: 0600

    - name: print instructions for initialisation repository
      debug:
              msg: cd ~ && gunzip -d /tmp/wordpress.tar.gz && tar -xf /tmp/wordpress.tar && cp /tmp/wp-config.php ./wordpress && cd wordpress && git init && git add * && git commit -m 'initial' && git branch -M main  && git -c http.sslVerify=false push https://root:"{{  gitlab_password.stdout  }}"@gitlab.netology.tech/root/wordpress main && cat /home/vagrant/diplom/devops-diplom/ansible/stack/.gitlab-ci.yml



