---
- name: install nginx
  hosts: gate.netology.tech
  become: true
  remote_user: vagrant
  roles:
   - nginx

- name: install app server with wordpress
  hosts: app.netology.tech
  gather_facts: yes
  become: true
  remote_user: vagrant
  roles:
    - server
    - wordpress
